# Generated by Django 2.2.12 on 2022-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=500)),
                ('experions', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100, unique=True)),
                ('personemails', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
