# Generated by Django 2.2.12 on 2022-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='websites',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
