# Generated by Django 2.2.12 on 2022-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experions', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobtype',
            name='experions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
