# Generated by Django 2.2.12 on 2022-09-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220920_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
