# Generated by Django 2.2.12 on 2022-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220920_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='locations',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
