# Generated by Django 4.1.1 on 2022-09-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_matchdata_personemails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='personemails',
            new_name='emails',
        ),
    ]
