# Generated by Django 4.1.1 on 2022-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_personemails_matchdata_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='percentage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
