# Generated by Django 4.1.1 on 2022-10-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_matchdata_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='job_Type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='job_Type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
