# Generated by Django 4.1.1 on 2022-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobtype_job_type_matchdata_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='emails',
            field=models.CharField(max_length=100),
        ),
    ]
