# Generated by Django 2.2.12 on 2022-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('personemails', models.CharField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=1000)),
                ('experions', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('websites', models.CharField(max_length=1000)),
                ('location', models.CharField(default='nill', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobType_json1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=500)),
                ('locations', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Matchdata_json1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
