# Generated by Django 2.2.12 on 2022-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate1',
            name='personemails',
            field=models.CharField(max_length=100),
        ),
    ]
