# Generated by Django 2.2.12 on 2022-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_candidate_data_jobtype_data_matchdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_data',
            name='personemails',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
